name: Build and Push Containers
on:
  push:    
    branches: [ main ]

jobs:
  build_push_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # For git clone
      packages: write  # For GHCR push
      id-token: write  # For OIDC auth
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #--v4.2.1

      - name: Build and push service image
        uses: ./.github/actions/docker_build
        with:
          image_tag: latest
          service: iamlive-gitlab-ci-service
          dockerfile: Dockerfile
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      #--Uncomment below if you want to build a test consumer container
      # - name: Build and push consumer image
      #   uses: ./.github/actions/docker_build
      #   with:
      #     image_tag: latest
      #     service: iamlive-gitlab-ci-test-consumer
      #     dockerfile: Dockerfile.consumer
      #     github_token: ${{ secrets.GITHUB_TOKEN }}